{% set version = "0.0-2" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-rebus.unicode
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/rebus.unicode_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/rebus.unicode/rebus.unicode_{{ version }}.tar.gz
  sha256: b5c9cf237174fdfc0598bc35fdb8a35ffd0ee5452737d79a32f77e02f908a3a0

build:
  noarch: generic
  merge_build_host: true  # [win]
  number: 1005
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  host:
    - r-base
    - r-rebus.base >=0.0_2
  run:
    - r-base
    - r-rebus.base >=0.0_2

test:
  commands:
    - $R -e "library('rebus.unicode')"           # [not win]
    - "\"%R%\" -e \"library('rebus.unicode')\""  # [win]

about:
  home: https://CRAN.R-project.org/package=rebus.unicode
  license: Unlimited
  summary: Build regular expressions piece by piece using human readable code. This package contains Unicode functionality, and is primarily intended to be used by package developers.
  license_family: Other
  license_file:
    - LICENSE

extra:
  recipe-maintainers:
    - conda-forge/r
